export const whatsappNumber = '918248353061'

export const site = {
  name: 'MS Homestays',
  location: 'Narasipuram, Tamil Nadu',
  strapline: 'A serene escape near Isha Adiyogi',
  distance: 'Approximately 6 km from Isha Yoga Center',
  intro:
    'Set among coconut groves, garden views and the cool mountain breeze of the Velliangiri foothills, MS Homestays offers calm, self contained rooms and studios for families, yoga seekers, students and remote workers.',
}

export const homestayAmenities = [
  { title: 'Free fast Wi-Fi', note: 'Reliable connectivity across the stay for work, calls and quiet evenings online.' },
  { title: 'Free drinking water', note: 'Clean drinking water available for guests throughout the stay.' },
  { title: 'Electric scooter rental', note: 'A convenient local mobility option for short trips around the area.' },
  { title: 'Home cooked pure vegetarian meals', note: 'Fresh house meals can be arranged on request for an extra charge.' },
  { title: 'Free washing machine', note: 'Useful for longer visits, family stays and yoga travel itineraries.' },
  { title: 'Yoga practice space', note: 'A calm shared area that guests may use freely for sadhana or stretching.' },
  { title: '24 hour check-in service', note: 'Flexible arrivals are supported when shared with the host in advance.' },
  { title: 'Airport pick up', note: 'Transport can be arranged at an extra charge for smoother arrivals.' },
  { title: 'Airport drop off', note: 'Return transfer support is available at an extra charge when needed.' },
]

const remoteImages = {
  gfRoom: [
    'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTAwMTM0MTIyNjA3OTMwNjUxMg%3D%3D/original/4a8d4745-3718-45ba-95ef-84949749e2eb.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTAwMTM0MTIyNjA3OTMwNjUxMg%3D%3D/original/d6786935-e837-412f-a671-8dd54dc9b7dc.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/miso/Hosting-860047998678873125/original/c0af3d11-c3f0-4562-94ba-de23518b7e6c.jpeg?im_w=1200',
  ],
  room2: [
    'https://a0.muscache.com/im/pictures/f43d1685-ab2a-4467-aaf5-1a80f67ad874.jpg?im_w=1200',
    'https://a0.muscache.com/im/pictures/miso/Hosting-860047998678873125/original/401359d5-aa8e-41a8-8ca3-39509d7fc6e2.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTAwMTM0MTIyNjA3OTMwNjUxMg%3D%3D/original/d6786935-e837-412f-a671-8dd54dc9b7dc.jpeg?im_w=1200',
  ],
  room3: [
    'https://a0.muscache.com/im/pictures/b38e9ab1-c3fb-4e75-b70c-f202d8a56ca6.jpg?im_w=1200',
    'https://a0.muscache.com/im/pictures/miso/Hosting-861563511129794122/original/7ec8e0cd-dd47-4f2a-af98-fe6771a2690a.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/miso/Hosting-860047998678873125/original/c0af3d11-c3f0-4562-94ba-de23518b7e6c.jpeg?im_w=1200',
  ],
  room4: [
    'https://a0.muscache.com/im/pictures/miso/Hosting-860689522138067361/original/f2f13833-a989-4678-a6c1-a5337c011e65.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/miso/Hosting-860689522138067361/original/9c4b9cc5-f62b-43dc-806c-27d41b8be88c.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6ODYxNjIzNTA3MTM4MjcyODk4/original/b379ddf8-f919-41dd-993b-d2753cbca9e9.jpeg?im_w=1200',
  ],
  room5: [
    'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6ODYxNjIzNTA3MTM4MjcyODk4/original/84a7d0cb-c519-4343-a2d7-83ba3d5e9ac2.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6ODYxNjIzNTA3MTM4MjcyODk4/original/a18fb574-361d-4967-a113-a9643e796ea5.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6ODYxNjIzNTA3MTM4MjcyODk4/original/b379ddf8-f919-41dd-993b-d2753cbca9e9.jpeg?im_w=1200',
  ],
  room7: [
    'https://a0.muscache.com/im/pictures/miso/Hosting-1015821438848359875/original/b0080d8f-1839-4448-8bd2-ce5d13bd8705.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/miso/Hosting-1015821438848359875/original/16598dcd-460d-44ed-81c8-0b7c3974b23c.jpeg?im_w=1200',
    'https://a0.muscache.com/im/pictures/miso/Hosting-1015821438848359875/original/10a829e7-9f3f-469e-b3da-ad4893bcbf54.jpeg?im_w=1200',
  ],
}

export const apartments = [
  {
    slug: 'ground-floor-couples-room',
    room: 'Ground Floor Couples Room',
    title: 'Simple Ground Floor Stay',
    subtitle: 'A calm room for two with kitchen access, verandah living and shared garden spaces.',
    sourceUrl: 'https://www.airbnb.com/h/mshomestays-near-isha-adiyogi-ground-floor-couples-room',
    guests: 2,
    beds: '2 single beds and 1 couch',
    baths: '2 shared bathrooms',
    size: 'Ground floor private room',
    type: 'Private room in home',
    images: remoteImages.gfRoom,
    amenities: ['Mountain view', 'Garden view', 'Kitchen', 'Wifi', 'Free parking', 'Self check in', 'Verandah', 'Shared terrace sadhana space', 'Washing machine access'],
  },
  {
    slug: 'room-no-2-cozy-room',
    room: 'Room No 2',
    title: 'Cozy Room',
    subtitle: 'A quiet ground floor room with private entry, attached bathroom and high speed WiFi.',
    sourceUrl: 'https://www.airbnb.com/h/mshomestays-near-isha-adiyogi-cozyroom',
    guests: 3,
    beds: '1 king bed and 1 single bed',
    baths: 'Private attached bathroom',
    size: 'Private room',
    type: 'Room in a home',
    images: remoteImages.room2,
    amenities: ['Mountain view', 'Garden view', 'Wifi', 'Free parking', 'Washing machine', 'Private entry', 'Attached bathroom', 'Verandah', 'Shared garden'],
  },
  {
    slug: 'room-no-3-family-studio',
    room: 'Room No 3',
    title: 'GF AC Family Studio',
    subtitle: 'An air conditioned studio with a private entrance, open kitchen and garden views.',
    sourceUrl: 'https://www.airbnb.com/h/mshomestays-near-isha-adiyogi-family-studio1',
    guests: 5,
    beds: '1 king bed, 1 queen bed and 1 couch',
    baths: '1 bath',
    size: 'Entire ground floor studio',
    type: 'Entire home',
    images: remoteImages.room3,
    amenities: ['Air conditioning', 'Kitchen', 'Fridge', 'Stove', 'Wifi', 'Free parking', 'Private entrance', 'Garden view', 'Terrace sadhana space'],
  },
  {
    slug: 'room-no-4-family-studio',
    room: 'Room No 4',
    title: 'FF AC Family Studio',
    subtitle: 'A first floor studio with balcony, open kitchen and a generous family sleeping layout.',
    sourceUrl: 'https://www.airbnb.com/h/mshomestays-near-isha-adiyogi-family-studio2',
    guests: 4,
    beds: '1 king bed and 1 queen bed',
    baths: '1 bath',
    size: 'First floor air conditioned studio',
    type: 'Entire studio',
    images: remoteImages.room4,
    amenities: ['Air conditioning', 'Kitchen', 'Balcony', 'Wifi', 'Free parking', 'Garden view', 'Mountain breeze', 'Self check in', 'Family friendly'],
  },
  {
    slug: 'room-no-5-couples-home',
    room: 'Room No 5',
    title: 'AC Couples Home',
    subtitle: 'A private air conditioned home with balcony, reading space and views toward the hills.',
    sourceUrl: 'https://www.airbnb.com/h/mshomestays-near-isha-adiyogi-couples-home',
    guests: 3,
    beds: '1 king bed',
    baths: '1 bath',
    size: 'Private AC home',
    type: 'Entire home',
    images: remoteImages.room5,
    amenities: ['Air conditioning', 'Kitchen', 'Reading space', 'Balcony', 'Wifi', 'Free parking', 'Hill view', 'Self check in', 'Peaceful work space'],
  },
  {
    slug: 'room-no-7-wfh-room',
    room: 'Room No 7',
    title: 'WFH Room',
    subtitle: 'A compact, quiet room designed for remote work and short mindful stays.',
    sourceUrl: 'https://www.airbnb.com/h/mshomestays-near-isha-adiyogi-wfh-room',
    guests: 2,
    beds: 'Day bed sleeping setup',
    baths: 'Shared or nearby bathroom',
    size: 'Work friendly private room',
    type: 'Private room',
    images: remoteImages.room7,
    amenities: ['Wifi', 'Desk', 'Quiet room', 'Balcony access', 'Garden view', 'Free parking', 'Mountain breeze', 'Shared terrace', 'Short stay friendly'],
  },
]
